name = "courtiq"
main = ".open-next/worker.js"
compatibility_date = "2026-07-04"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_APP_NAME = "Court IQ"

[[d1_databases]]
binding = "DB"
database_name = "courtiq-db"
database_id = "dc700118-e2de-4d6b-9151-91cece31d199"
